# Generated by Django 4.2.6 on 2023-10-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pageCount', models.PositiveIntegerField()),
                ('publishedDate', models.DateTimeField()),
                ('thumbnailUrl', models.URLField(max_length=255)),
                ('shortDescription', models.TextField()),
                ('longDescription', models.TextField()),
                ('status', models.CharField(choices=[('PUBLISH', 'Publish'), ('MEAP', 'Meap')], max_length=10)),
                ('authors', models.ManyToManyField(related_name='books', to='books_store.author')),
                ('categories', models.ManyToManyField(related_name='books', to='books_store.category')),
            ],
        ),
    ]
