# Generated by Django 4.2.6 on 2023-10-27 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_store', '0003_bookrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('currently_reading', models.ManyToManyField(blank=True, related_name='users_currently_reading', to='books_store.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_read', models.ManyToManyField(blank=True, related_name='users_want_to_read', to='books_store.book')),
            ],
        ),
    ]
