# Generated by Django 4.2.6 on 2023-10-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
