# Generated by Django 4.2.6 on 2023-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
