# Generated by Django 4.2.6 on 2023-10-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0008_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_images/'),
        ),
    ]
