# Generated by Django 4.2.6 on 2023-10-28 16:00

import books_store.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0009_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to=books_store.utils.profile_image_path),
        ),
    ]
